import "./src/styles/global.css"
import "./src/styles/landing.css"
import "./src/styles/team.css"
import "./src/styles/menu.css"
import "./src/styles/header.css"
import "./src/styles/package.css"
import "./src/styles/backButton.css"
import "./src/styles/headingList.css"
